### ISSUE TITLE
API doesn't work anymore

### ISSUE THREAD

**Issue by AlexBarbulescu** [LostPolygon/Unity-Publisher-API-PHP#7]
Unity might have pushed another security update. The API no longer work.
'Fetching publisher data failed, error code 401 (Unauthorized)'

Alex Barbulescu

**Comment by AlexBarbulescu** [comment]
> Authentication for Publisher Administration has been changed to use the centralized Unity ID authentication used throughout Unity services.

**Comment by AlexBarbulescu** [comment]
A temporary fix for login with token, till an update is available. Change the lines to :
```
line 7 :     const LOGIN_URL = 'https://id.unity.com/';
line 33 :         $this->cookies['kharma_session'] = $this->GetXUnitySessionCookie();
line 51 :         unset($this->cookies['kharma_session']);
```

**Comment by LostPolygon** [comment]
Ugh... Thanks for letting me know, I guess this one will be much harder to
fix, but I'll start ASAP.

On Sep 28, 2016 11:47 AM, "Alex Barbulescu" <notifications@github.com>
wrote:

Unity might have pushed another security update. The API no longer work.
'Fetching publisher data failed, error code 401 (Unauthorized)'

Alex Barbulescu

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LostPolygon/Unity-Publisher-API-PHP/issues/7>, or mute
the thread

**Comment by kiranmaya** [comment]
eagerly waiting for your Update .

**Comment by LostPolygon** [comment]
Fixed in https://github.com/LostPolygon/Unity-Publisher-API-PHP/commit/2a1e0f417708fa51f35aa56182156c84542b2488.

**Comment by AlexBarbulescu** [comment]
:D thank you for the fix.
